### ISSUE TITLE
libnice unit tests fails on alpine

### ISSUE THREAD

**Issue by nswarnkar** [shadeslayer/libnice#1]
Hi,

This problem we observed when we found Janus WebRTC was not working on Alpine.

https://github.com/meetecho/janus-gateway/issues/907#issuecomment-304296449

By digging dipper, we found that it was crashing in libnice. Please find below the equivalent crash dump, which we observed with unit tests as well ( by pastbin url).

https://pastebin.com/embed_js/1mj4ULCy

Also the reports of test suite.

## ### ============================================
   libnice 0.1.14.1: tests/test-suite.log
============================================

### # TOTAL: 29
PASS:  20
 SKIP:  0
 XFAIL: 0
 FAIL:  9
 XPASS: 0
 ERROR: 0

.. contents:: :depth: 2

FAIL: test-pseudotcp
====================

(process:7002): libnice-tests-ERROR **: Socket 0x7fc85c341460 Closed : 104
Trace/breakpoint trap (core dumped)
FAIL test-pseudotcp (exit status: 133)

FAIL: test-io-stream-thread
===========================

Segmentation fault (core dumped)
FAIL test-io-stream-thread (exit status: 139)

FAIL: test-io-stream-closing-write
==================================

Segmentation fault (core dumped)
FAIL test-io-stream-closing-write (exit status: 139)

FAIL: test-io-stream-closing-read
=================================

Segmentation fault (core dumped)
FAIL test-io-stream-closing-read (exit status: 139)

Fixing the crash issue on Alpine will be of great help.

Thanks

**Comment by giordanocardillo** [comment]
I ran tests on (docker image) Alpine from 3.2 to 3.6 for libnice from v0.1.8 to v0.1.14. You can find all the test-suite logs here [Dropbox folder](https://www.dropbox.com/sh/oc8ki58tuo3gyv1/AAC5NVKorNOqzdWpuboaFUy7a?dl=0). All the tests show more than one segmentation fault on this linux distribution.

Hope this helps.

P.S. The script I made to run this tests inside containers is the following:

```bash
#!/bin/sh

COMMIT_HASHES="3fe60efd08a81f5f11cd4ebede20264bbe59f1b1 9f9f713a4ea7a5dd883bf0de18f520fa308e52a4 2a9ce5498e2c98488e525c43596bd050b327b5bc 22ebcbaab527ed8f8c726d4abbf197b16359f202 f79bdd963686e8f3103e4675a16773c6c8d994e6 fc41eedfcd7961d8ebb0002e2007f292ed6ceb82 6bfea0d063fb358a44e8800eae314520a2babd61"

apk update
apk add glib-dev git autoconf automake gtk-doc g++ libtool make gnutls-dev
cd /root
git clone https://github.com/libnice/libnice.git

for HASH in $COMMIT_HASHES; do
  cd libnice
  git reset --hard
  git checkout $HASH 
  ./autogen.sh && make && make check
  LIBNICE_VERSION=$(awk 'NR==2{gsub(/\:/,""); print $2}' tests/test-suite.log)
  cp tests/test-suite.log /root/tests/test-suite-$LIBNICE_VERSION.log
  cd ..
done
```
The used commit hashes are the ones from the releases page

**Comment by shadeslayer** [comment]
Hi
Please report a bug on the libnice project on the Freedesktop Phabricator instance here : https://phabricator.freedesktop.org/project/profile/20/

**Comment by shadeslayer** [comment]
FWIW I tried to run the tests, it seems like the tests fail to even enter main() here https://github.com/libnice/libnice/blob/master/tests/test-send-recv.c#L1163

At a quick glance, this feels more like a libc issue than a libnice issue

```
~/libnice-0.1.14 # gdb ./tests/test-send-recv
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-alpine-linux-musl".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./tests/test-send-recv...done.
(gdb) b 1163
Breakpoint 1 at 0x63be: file test-send-recv.c, line 1163.
(gdb) r
Starting program: /root/libnice-0.1.14/tests/test-send-recv 
warning: Error disabling address space randomization: Operation not permitted
During startup program terminated with signal SIGSEGV, Segmentation fault.
(gdb) 
```

**Comment by giordanocardillo** [comment]
Thank you @shadeslayer!

**Comment by nswarnkar** [comment]
I changed the stack size in glib, only one test fails that test-pseudotcp, all other passes now.

### ============================================
   libnice 0.1.14.1: tests/test-suite.log
============================================

# TOTAL: 29
# PASS:  28
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-pseudotcp
====================


(process:30996): libnice-tests-ERROR **: Socket 0x7f804e251660 Closed : 104
Trace/breakpoint trap (core dumped)
FAIL test-pseudotcp (exit status: 133)

So one doubt over stack size in Alpine seems to correct many problems, rather than changing the al software...So above one crash is what is required to be fixed.

**Comment by shadeslayer** [comment]
Could you run that test under gdb and paste the backtrace to the mailing list?

**Comment by nswarnkar** [comment]
This I got in test-suite.log:
******************************
============================================
   libnice 0.1.14.1: tests/test-suite.log
============================================

# TOTAL: 29
# PASS:  28
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test-pseudotcp
====================


(process:30996): libnice-tests-ERROR **: Socket 0x7f804e251660 Closed : 104
Trace/breakpoint trap (core dumped)
FAIL test-pseudotcp (exit status: 133)


This I got with GDB
***********************

Starting program: /root/libnice/tests/test-pseudotcp

(process:8743): libnice-tests-ERROR **: Socket 0x555555765660 Closed : 104

Program received signal SIGTRAP, Trace/breakpoint trap.
_g_log_abort (breakpoint=1) at gmessages.c:549
549     }
(gdb) bt
#0  0x00007ffff7857c21 in _g_log_abort (breakpoint=1) at gmessages.c:549
#1  0x00007ffff7858c18 in g_log_default_handler
(log_domain=log_domain@entry=0x55555555ad36
"libnice-tests", log_level=log_level@entry=6,
message=message@entry=0x5555557b57c0
"Socket 0x555555765660 Closed : 104", unused_data=unused_data@entry=0x0) at
gmessages.c:3036
#2  0x00007ffff7858e34 in g_logv (log_domain=0x55555555ad36
"libnice-tests", log_level=G_LOG_LEVEL_ERROR, format=<optimized out>,
args=args@entry=0x7fffffffe920) at gmessages.c:1336
#3  0x00007ffff785903f in g_log (log_domain=<optimized out>,
log_level=<optimized out>, format=<optimized out>) at gmessages.c:1398
#4  0x0000555555555cc4 in closed (sock=<optimized out>, err=<optimized
out>, data=<optimized out>) at test-pseudotcp.c:163
#5  0x00005555555580b6 in process (seg=<synthetic pointer>,
self=0x555555765660 [PseudoTcpSocket]) at pseudotcp.c:1628
#6  0x00005555555580b6 in parse (self=self@entry=0x555555765660
[PseudoTcpSocket], _header_buf=_header_buf@entry=0x555555765fac "",
data_buf=data_buf@entry=0x555555765fc4 "ck to 4000 mA",
data_buf_len=data_buf_len@entry=0, header_buf_len=24) at pseudotcp.c:1506
#7  0x000055555555a358 in parse (data_buf_len=0, data_buf=0x555555765fc4
"ck to 4000 mA", header_buf_len=24, _header_buf=0x555555765fac "",
self=0x555555765660 [PseudoTcpSocket]) at pseudotcp.c:1061
#8  0x000055555555a358 in pseudo_tcp_socket_notify_packet
(self=0x555555765660 [PseudoTcpSocket], buffer=0x555555765fac "", len=24)
    at pseudotcp.c:1061
#9  0x0000555555556233 in notify_packet (user_data=0x555555765fa0) at
test-pseudotcp.c:176
#10 0x00007ffff785205a in g_main_dispatch (context=0x5555557652c0) at
gmain.c:3148
#11 0x00007ffff785205a in g_main_context_dispatch
(context=context@entry=0x5555557652c0)
at gmain.c:3813
#12 0x00007ffff7852418 in g_main_context_iterate (context=0x5555557652c0,
block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at
gmain.c:3886
#13 0x00007ffff7852742 in g_main_loop_run (loop=0x7ffff7b1df80) at
gmain.c:4082
#14 0x0000555555555a9d in main (argc=1, argv=0x7fffffffecb8) at
test-pseudotcp.c:282
(gdb)
